---
sudo: required

language: java

jdk:
  - oraclejdk8

after_success:
  - mvn -P coveralls coveralls:report

before_install:
  - curl -fsSL https://get.docker.com/ | sh
  - usermod -aG docker travis

script: 
  - scripts/build_mvn_runner.sh
  - ./test.sh
