---
sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

after_success:
  - mvn -P coveralls coveralls:report

script: 
  - scripts/build_mvn_runner.sh
  - scripts/mvn.sh -P code-coverage clean cobertura:cobertura-integration-test
