---
sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

after_success:
  - mvn -P coveralls coveralls:report

before_script:
  - docker --version

script: 
  - scripts/build_mvn_runner.sh
  - ./test.sh
